### ISSUE TITLE
developing nugo?

### ISSUE THREAD

**Issue by andryua** [cavaliercoder/nugo#1]
Hi!
Are You still developing nugo?
Thanks!

**Comment by cavaliercoder** [comment]
I would love to continue working on this project, but I abandoned it due to feasibility.

Stretching my memory a little, but the primary issue was that there is no solid OData implementation in Go. NuGet server uses the OData protocol to define search queries, output filters, etc. This project worked fine with a few pre-canned queries (like, list all packages) but implementation become tricky for implementing package search and filtering.

This is a project I would gladly revive if a solution presented itself. Thanks for asking!

**Comment by danesparza** [comment]
Hmmm ... would something like this help? https://github.com/crestonbunch/godata

**Comment by cavaliercoder** [comment]
Stretching my memory a little, but I recall testing with that package. Unfortunately, some of the required functionality is listed under _Work in progress_ and some of the implemented features weren't working correctly. I see it hasn't been updated since this time. A more adventurous traveller might be interested to revive this and try it out!?
